name: go
on:
  workflow_call:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.19', '1.20']
    steps:
      # Checkout repo to GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}

      # go test
      - name: Go Test
        run: make
